### ISSUE TITLE
Finding claims

### ISSUE THREAD

**Issue by Rezabagheriloye** [PatentsView/PatentsView-Code-Snippets#9]
Hi, 
As a university student working On my thesis, I want to find patent's claims according to the titles and abstracts or Publication Number code.
Is it possible with PatentsView?

**Comment by killahjones** [comment]
Hi! I would suggest that you first select the patent IDs that you are interested in using the patent.tsv table. This table includes the patent title and patent number. Once you've selected your subset of patents, I would merge them to the individual claims files. The year of claim file is going to correspond to the granted year in the patent table. 

Let me know if you have any additional questions. ~Christina
